language: ruby
cache: bundler

services:
  - redis-server

gemfile:
  - gemfiles/sidekiq_2.gemfile
  - gemfiles/sidekiq_3.gemfile
  - gemfiles/sidekiq_4.gemfile
  - gemfiles/sidekiq_5.gemfile

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0

notifications:
  email: false
